# vim:ft=kitty
## name: lumae Dusk
## author: Mae C.
## license: MIT
## upstream: https://maeirl.ie
## blurb: Mid-dark flavor — softer warm grey ground.
foreground #ede8e8
background #2f2b2b
cursor #f18eac
selection_background #4e4949
color0 #161212
color1 #f09584
color2 #68c892
color3 #cfac5c
color4 #82b5ed
color5 #f18eac
color6 #5dc5bd
color7 #ede8e8
color8 #6b6666
color9 #ffc3b7
color10 #a4e5bd
color11 #edd192
color12 #b3d8ff
color13 #cccffe
color14 #9fe3dd
color15 #fdf8f8
