# vim:ft=kitty
## name: lumae Earth Sand
## author: Mae C.
## license: MIT
## upstream: https://maeirl.ie
## blurb: Light warm/earthy flavor (Taupe ground).
foreground #16120f
background #fcf9f5
cursor #b62162
selection_background #ddd2c6
color0 #f0e8e0
color1 #ad3d2c
color2 #007d49
color3 #806419
color4 #406b98
color5 #b62162
color6 #0c7772
color7 #16120f
color8 #96887a
color9 #d36654
color10 #25a468
color11 #a88630
color12 #5e8ec2
color13 #7e7ce2
color14 #369d96
color15 #16120f
