# vim:ft=kitty
## name: lumae Earth Cocoa
## author: Mae C.
## license: MIT
## upstream: https://maeirl.ie
## blurb: Deep warm/earthy dark flavor (Taupe ground).
foreground #f0e8e0
background #16120f
cursor #f18eac
selection_background #52493f
color0 #322b25
color1 #f09584
color2 #68c892
color3 #cfac5c
color4 #82b5ed
color5 #f18eac
color6 #5dc5bd
color7 #f0e8e0
color8 #716659
color9 #ffc3b7
color10 #a4e5bd
color11 #edd192
color12 #b3d8ff
color13 #cccffe
color14 #9fe3dd
color15 #fcf9f5
