# vim:ft=kitty
## name: lumae Dusk
## author: Mae C.
## license: MIT
## upstream: https://maeirl.ie
## blurb: Mid-dark flavor — softer warm grey ground.
foreground #ede8e8
background #2f2b2b
cursor #f18eac
cursor_text_color #2f2b2b
selection_background #6b6666
selection_foreground #ede8e8
url_color #b4afaf
active_border_color #8e8989
inactive_border_color #4e4949
tab_bar_background #4e4949
active_tab_background #2f2b2b
active_tab_foreground #ede8e8
inactive_tab_background #4e4949
inactive_tab_foreground #b4afaf
wayland_titlebar_color #2f2b2b
macos_titlebar_color #2f2b2b
bell_border_color #cfac5c
mark1_background #cfac5c
mark1_foreground #2f2b2b
mark2_background #f18eac
mark2_foreground #2f2b2b
mark3_background #5dc5bd
mark3_foreground #2f2b2b
color0 #4e4949
color1 #f09584
color2 #68c892
color3 #cfac5c
color4 #82b5ed
color5 #f18eac
color6 #5dc5bd
color7 #ede8e8
color8 #8e8989
color9 #ffc3b7
color10 #a4e5bd
color11 #edd192
color12 #b3d8ff
color13 #cccffe
color14 #9fe3dd
color15 #fdf8f8
color16 #eb9c58
color17 #d693ea
color18 #4e4949
color19 #6b6666
color20 #b4afaf
color21 #fdf8f8
