[main]
font=Cantarell:size=12
prompt=" "
icon-theme=Papirus-Dark
layer=overlay
lines=8
width=40
horizontal-pad=12
vertical-pad=8
inner-pad=4

[colors]
# Catppuccin Macchiato
background=24273add
text=cad3f5ff
selection=f5bde6ff
selection-text=24273aff
border=f0c6c6ff
match=f5bde6ff

[border]
width=2
radius=12
