[colors]
ansi = [
    "#2f2b2b",
    "#f09584",
    "#68c892",
    "#cfac5c",
    "#82b5ed",
    "#f18eac",
    "#5dc5bd",
    "#ede8e8",
]
background = "#161212"
brights = [
    "#6b6666",
    "#ffc3b7",
    "#a4e5bd",
    "#edd192",
    "#b3d8ff",
    "#d693ea",
    "#9fe3dd",
    "#fdf8f8",
]
compose_cursor = "#ede8e8"
cursor_bg = "#ede8e8"
cursor_border = "#ede8e8"
cursor_fg = "#161212"
foreground = "#ede8e8"
scrollbar_thumb = "#ede8e8"
selection_bg = "#ede8e8"
selection_fg = "#161212"
split = "#6b6666"
visual_bell = "#2f2b2b"

[colors.indexed]
16 = "#d693ea"
17 = "#ede8e8"

[colors.tab_bar]
background = "#161212"
inactive_tab_edge = "#ede8e8"

[colors.tab_bar.active_tab]
bg_color = "#f18eac"
fg_color = "#161212"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#161212"
fg_color = "#ede8e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#161212"
fg_color = "#ede8e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#ede8e8"
fg_color = "#ede8e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#6b6666"
fg_color = "#ede8e8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
