config_version = 8

[audio]
enable_sounds = true

[bar.default]
center = [ "clock", "audio_visualizer" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "keyboard_layout",
    "control-center",
    "session"
]
margin_ends = 8
scale = 1.1000000089406967
start = [ "launcher", "active_window", "wallpaper", "workspaces", "mae/sysmon:sysmon" ]

[control_center.calendar]
show_week_numbers = true

[dock]
enabled = true
icon_size = 36
launcher_position = "start"
reserve_space = false
show_dots = true
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[nightlight]
enabled = true

[osd]
offset_y = 128
orientation = "vertical"
position = "bottom_center"
position_vertical = "center_right"

[plugins]
enabled = [ "mae/sysmon" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/cadrianmae/.local/state/noctalia/plugins/sources/local"
    name = "local"

[shell]
avatar_path = "/var/lib/AccountsService/icons/cadrianmae"
panel_anchor_bar = "default"
polkit_agent = true

    [shell.panel]
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl hibernate"
    countdown_seconds = 0.0
    enabled = true
    glyph = "hibernate"
    label = "Hibernate"
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "6"
    variant = "destructive"

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
custom_palette = "Lumae-Midnight"
mode = "dark"
source = "custom"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "niri", "qt", "wezterm" ]

[wallpaper]
directory = "/home/cadrianmae/Pictures/Wallpaper 2024"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/cadrianmae/Pictures/Wallpaper 2024/andrea-de-santis-V_RnZ09HZb4-unsplash.jpg"

    [wallpaper.last]
    path = "/home/cadrianmae/Pictures/Wallpaper 2024/andrea-de-santis-V_RnZ09HZb4-unsplash.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/cadrianmae/Pictures/Wallpaper 2024/andrea-de-santis-V_RnZ09HZb4-unsplash.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/cadrianmae/Pictures/Wallpaper 2024/andrea-de-santis-V_RnZ09HZb4-unsplash.jpg"

[widget.active_window]
max_length = 128
min_length = 128
show_empty_label = true
title_scroll = "on_hover"

[widget.audio_visualizer]
bands = 24
color_2 = "secondary"
interactive = false
mirrored = false
width = 96

[widget.brightness]
show_label = false

[widget.clock]
anchor = true
format = "{:%T %W %a %-d %b} "
tooltip_format = "{:%c}"

[widget.media]
capsule = true
hide_when_no_media = true
max_length = 192
min_length = 192
title_scroll = "always"

[widget.network]
show_label = false
vpn_status = "both"

[widget.tray]
capsule = true

[widget.volume]
show_label = false